### ISSUE TITLE
ListMetadataFormats yields a idDoesNotExist error in the case of an "empty" repository

### ISSUE THREAD

**Issue by RKrahl** [icatproject/icat.oaipmh#4]
In the case of an "empty" repository, e.g. an ICAT having no objects of a configured type, the `ListMetadataFormats` call returns an `idDoesNotExist` error.

I have a similar case as in #3, e.g. icat.oaipmh configured for Investigations, but no Investigation in ICAT is visible for icat.oaipmh.  When I call `ListMetadataFormats` with no arguments, I get the following :
```lang=xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="https://oai.datacite.org/xsl/oaitohtml.xsl"?>
<OAI-PMH xmlns="http://www.openarchives.org/OAI/2.0/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd">
    <responseDate>2019-07-25T11:18:23Z</responseDate>
    <request verb="ListMetadataFormats">https://icat-test.helmholtz-berlin.de/oaipmh/request</request>
    <error code="idDoesNotExist">Identifier 'null' is unknown or illegal in this repository</error>
</OAI-PMH>
```

According to OAI-PMH this error is defined as:

> idDoesNotExist - The value of the identifier argument is unknown or illegal in this repository.

But this request did not have an identifier argument.

**Comment by EmilJunker** [comment]
1d8309995551ce3b562272a81a09c2a4087ff0a3 should fix this issue
